Feature/stored preferences
dashxhq/dashx-ios pull request #5
Opened 2022-07-22 14:18 UTC by itsnaidu

- Implemented stored preferences
  - Queries for fetching and saving stored preference 
  - Updated schema, and API with new queries
  - Updated DashXClient with stored preference calls
- Resolved issues with the Packages
  - Updated the Apollo client package version
  - Added target dependencies to fix issues with the SPM
  - Forced issues fixed in a couple of files

2022-07-22 14:22 UTC, itsnaidu commented
We have to update the Readme:

For schema download with:
`apollo schema:download --endpoint="https://api.dashx-staging.com/graphql" Sources/DashX/schema.json`

For codegen with:
`apollo client:codegen --target=swift --namespace=DashXGql --localSchemaFile=Sources/DashX/schema.json --includes="Graphql/*.graphql" --passthroughCustomScalars Sources/DashX/API.swift`


The user must be at the root folder of the repo to run the above commands

2022-07-25 08:02 UTC, RabidFire commented on Graphql/FetchStoredPreferences.graphql
> +query FetchStoredPreferences($input: FetchStoredPreferencesInput!){
Add space before `{`

2022-07-25 08:02 UTC, RabidFire commented on Graphql/FetchStoredPreferences.graphql
> +    fetchStoredPreferences(input: $input){
Add space before `{`

2022-07-25 08:02 UTC, RabidFire commented on Graphql/SaveStoredPreferences.graphql
> +mutation SaveStoredPreferences($input: SaveStoredPreferencesInput!){
Add space before `{`

2022-07-25 08:04 UTC, RabidFire commented on Sources/DashX/DashXClient.swift
> +         */
- Add setIdentity
- Remove `uid` as a parameter
- Pick `uid` from options["uid"] if present, or else use self.uid
- Same goes for `anonymousUid` - pick from options["anonymousUid"] if present, or else use self.anonymousUid
-

2022-07-25 08:04 UTC, RabidFire commented on Sources/DashX/DashXClient.swift
> +              let json = graphQLResult.data?.fetchStoredPreferences
Return the `preferenceData` within `graphQLResult.data?.fetchStoredPreferences`

2022-07-25 08:05 UTC, RabidFire commented on Sources/DashX/DashXClient.swift
> +              let json = graphQLResult.data?.saveStoredPreferences
Return the `preferenceData` within `graphQLResult.data?.saveStoredPreferences`

2022-07-25 08:06 UTC, RabidFire requested changes
- Delete schema.json file. Commit.
- After comitting, then add to .gitignore so that future devs don't re-add.
- Ensure you commit the deletion before making gitignore changes, else you'll have to force remove the file using `git rm`.

2022-07-25 09:54 UTC, itsnaidu commented
> * Delete schema.json file. Commit.
> * After comitting, then add to .gitignore so that future devs don't re-add.
> * Ensure you commit the deletion before making gitignore changes, else you'll have to force remove the file using `git rm`.

Sure

2022-07-26 04:44 UTC, RabidFire commented on Sources/DashX/DashXClient.swift
>      }
```
public func setIdentity(uid, token) {

}
```

2022-07-26 04:44 UTC, RabidFire commented on Sources/DashX/DashXClient.swift
> +        self.uid = uid
Rename the private variables: https://github.com/dashxhq/dashx-browser/blob/main/src/Client.ts#L28-L32

2022-07-26 04:45 UTC, RabidFire commented on Sources/DashX/DashXClient.swift
> +              let json = graphQLResult.data?.fetchCart
De-indent

2022-07-26 04:45 UTC, RabidFire commented on Sources/DashX/DashXClient.swift
> +              let json = graphQLResult.data?.saveStoredPreferences
Comment not addressed

2022-07-26 04:46 UTC, RabidFire commented on Sources/DashX/DashXClient.swift
>      }
https://github.com/dashxhq/dashx-browser/blob/main/src/Client.ts#L117-L120

2022-07-26 16:34 UTC, merged